chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chat/create/', views.CreateRoomView.as_view(), name='create_room'),
    path('chat/<slug:room_slug>/', views.RoomView.as_view(), name='room'),
]

chatty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from profiles.views import RegisterView, CustomLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', include('profiles.urls', namespace='profiles')),
    path('', include('chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from channels.db import database_sync_to_async


class ChatRoom(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name='chat_rooms', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chat:room', args=[self.slug])


class ChatMessage(models.Model):
    room = models.ForeignKey(
        ChatRoom, on_delete=models.CASCADE, related_name='messages')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_messages')
    message_content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} - {self.room.name} - {self.message_content}'

chat/forms.py
from django import forms
from .models import ChatRoom


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = ChatRoom
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs):
        super(CreateRoomForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'placeholder': 'Room name',
             'class': 'form-control'})
        self.fields['description'].widget.attrs.update(
            {'placeholder': 'Room description',
             'class': 'form-control'})

chat/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.text import slugify
from .models import ChatRoom, ChatMessage
from django.views.generic import TemplateView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateRoomForm


class HomeView(TemplateView):
    template_name = 'chat/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rooms'] = ChatRoom.objects.all()
        search_query = self.request.GET.get('q', None)
        if search_query:
            context['rooms'] = context['rooms'].filter(
                name__icontains=search_query)
        return context


class RoomView(DetailView):
    model = ChatRoom
    template_name = 'chat/room.html'
    context_object_name = 'room'

    def get_object(self, queryset=None):
        return ChatRoom.objects.get(slug=self.kwargs.get('room_slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = ChatMessage.objects.filter(
            room=self.get_object())
        context['users'] = self.get_object().users.all()
        return context


class CreateRoomView(LoginRequiredMixin, CreateView):
    model = ChatRoom
    form_class = CreateRoomForm
    template_name = 'chat/create_room.html'
    success_url = reverse_lazy('chat:home')
    
    def form_valid(self, form):
        room = form.save(commit=False)
        room.slug = slugify(room.name)
        print(room.slug)
        room.save()
        return super().form_valid(form)

chat/templates/chat/create_room.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2 class="text-center mb-5">Create a Room</h2>
      <form method="post" action="{% url 'chat:create_room' %}">
        {% csrf_token %}
        <div class="form-group">
          {{ form }}
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

chat/templates/chat/home.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1 class="text-center mb-5">Welcome to Chatty</h1>
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Create a New Room</h5>
          <a href="{% url 'chat:create_room' %}" class="btn btn-success">Create Room</a>
        </div>
      </div>
      <div class="card-deck">
        {% for room in rooms %}
        <div class="card mb-4">
          <div class="card-body">
            <h5 class="card-title">{{ room.name }}</h5>
            <p class="card-text">{{ room.description }}</p>
            <a href="{{ room.get_absolute_url }}" class="btn btn-primary">Join Chat</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

chat/templates/chat/room.html
{% extends 'index.html' %}
{% block content %}
<style>
  #chat-messages {
    height: 600px;
    overflow-y: scroll;
    display: flex;
    flex-direction: column;
  }

  #chat-messages li {
    padding: 8px;
    margin: 4px;
    border-radius: 16px;
    max-width: 70%;
    display: flex;
    flex-direction: column;
  }

  #chat-messages .message-bubble {
    padding: 8px;
    border-radius: 16px;
    background-color: #2E3840;
    font-size: 1.1em;
    line-height: 1.3em;
  }

  #chat-messages .user-message {
    align-self: flex-end;
    background-color: #f0f0f5;
    color: black;
  }

  #chat-messages .other-user-message {
    align-self: flex-start;
    background-color: #f0f0f5;
  }

  #chat-messages .message-info {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    margin-bottom: 4px;
  }

  #chat-messages .message-info img {
    width: 32px;
    height: 32px;
    margin-right: 8px;
    border-radius: 50%;
  }
  .message-info img {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin-right: 10px;
  }
</style>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8">
      <h1 class="mb-4">{{ room.name }}</h1>
      <div class="card mb-4">
        <div class="card-body">
          <ul id="chat-messages" class="list-unstyled mb-0">
            {% for message in messages %}
              <li class="{% if message.user == request.user %}user-message{% else %}other-user-message{% endif %}">
                <div class="message-info">
                  <img src="{{ message.user.profile.profile_image.url }}" alt="{{ message.user.username }} profile image">
                  <span>{{ message.user.username }}</span>
                </div>
                <div class="message-bubble">{{ message.message_content }}</div>
              </li>
            {% endfor %}            
          </ul>
        </div>
      </div>
      <form id="chat-form">
        <div class="input-group mb-3">
          <input
            type="text"
            id="chat-input"
            class="form-control"
            placeholder="Type a message..."
          />
          <button type="submit" id="chat-submit" class="btn btn-primary">
            Send
          </button>
        </div>
      </form>
    </div>
    <div class="col-md-4">
      <h3 class="mb-3">Users in Chat</h3>
      <div class="card mb-4">
        <div class="card-body">
          <ul id="chat-users" class="list-unstyled mb-0">
            {% for user in users %}
              <li>
                <div class="message-info">
                  <img src="{{ user.profile.profile_image.url }}" alt="{{ user.username }} profile image" width="50" height="50">
                  <span>{{ user.profile.username }}</span>
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{{ room.slug|json_script:"roomname" }} 
{{ request.user.username|json_script:"username" }}
<script>
  const roomName = JSON.parse(document.getElementById("roomname").textContent);
  const userName = JSON.parse(document.getElementById("username").textContent);
  const chatSocket = new WebSocket(
    "ws://" + window.location.host + "/ws/chat/" + roomName + "/"
  );
  
  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    const message = data["message"];
    const chatMessages = document.getElementById("chat-messages");
    const users = data["users"];
    const messageElement = document.createElement("li");
    messageElement.innerText = data["username"] + ": " + message;
    chatMessages.appendChild(messageElement);
    updateUsers(users);
  };
  
  
  chatSocket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  window.addEventListener('unload', () => {
    chatSocket.close();
  });  
  
  document.addEventListener("DOMContentLoaded", function() {
    const messageInput = document.getElementById("chat-input");
    messageInput.focus();
    scroll();
  });
  
  document.querySelector("#chat-form").addEventListener("submit", (e) => {
    e.preventDefault();
    const messageInput = document.getElementById("chat-input");
    const message = messageInput.value;
    chatSocket.send(
      JSON.stringify({ message: message, username: userName, room: roomName })
    );
    messageInput.value = "";
  });
  
  function updateUsers(users) {
    const chatUsers = document.getElementById("chat-users");
    const userElements = chatUsers.getElementsByTagName("li");
    const existingUsers = Array.from(userElements).map(elem => elem.innerText);
    users.forEach((user) => {
      if (!existingUsers.includes(user)) {
        const userElement = document.createElement("li");
        userElement.innerText = user;
        chatUsers.appendChild(userElement);
      }
    });
  }
  
  function scroll() {
    const chatMessages = document.getElementById("chat-messages");
    chatMessages.scrollTop = chatMessages.scrollHeight;
  }
  
</script>
{% endblock %}